name: Trigger auto deployment for amy-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/amy-container-app-AutoDeployTrigger-4bcbd264-7361-4131-9cc0-44a35a1380df.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AMYCONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AMYCONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AMYCONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: amyregistyr.azurecr.io
          registryUsername: ${{ secrets.AMYCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AMYCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: amy-container-app
          resourceGroup: cti-conenv-app0707
          imageToBuild: amyregistyr.azurecr.io/amy-container-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


