name: Trigger auto deployment for con-app8081

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/con-app8081-AutoDeployTrigger-12bec386-1408-4cb7-bce5-bf14c3390430.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CONAPP8081_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONAPP8081_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONAPP8081_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: amyregistry1028.azurecr.io
          registryUsername: ${{ secrets.CONAPP8081_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONAPP8081_REGISTRY_PASSWORD }}
          containerAppName: con-app8081
          resourceGroup: cti-containerapps-album-amy1028
          imageToBuild: amyregistry1028.azurecr.io/con-app8081:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


