name: Trigger auto deployment for conapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/conapp-AutoDeployTrigger-f06af6b3-77bb-485a-8d6f-e4b5e36fc8c3.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CONAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: acabuildregistry.azurecr.io
          registryUsername: ${{ secrets.CONAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONAPP_REGISTRY_PASSWORD }}
          containerAppName: conapp
          resourceGroup: con-test-app-env
          imageToBuild: acabuildregistry.azurecr.io/conapp:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


