name: Trigger auto deployment for containerapp-amy0707

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/containerapp-amy0707-AutoDeployTrigger-fded0b46-ccfc-4552-8d3f-16bd95a2323e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CONTAINERAPPAMY0707_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPAMY0707_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPAMY0707_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: cttestingregistry.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPAMY0707_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPAMY0707_REGISTRY_PASSWORD }}
          containerAppName: containerapp-amy0707
          resourceGroup: cti-app-con-env0707
          imageToBuild: cttestingregistry.azurecr.io/containerapp-amy0707:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


